site_name: Spotify

theme:
  name: 'rtd-dropdown'

pages:
    - Home: index.md

    - Pré-Rastreabilidade:
        - Rich Picture Spotify: Modulos/Pre_rastreabilidade/Rich picture/Rich-picture-spotify.md
        - Rich Picture Usuário: Modulos/Pre_rastreabilidade/Rich picture/Rich-picture-usuário.md
        - Modelo de Argumentação Artista: Modulos/Pre_rastreabilidade/Argumentacao/Argumentacao-artistas.md
        - Modelo de Argumentação Pagamento: Modulos/Pre_rastreabilidade/Argumentacao/Argumentacao-pagamento.md

    - Elicitação:
        - Elicitação de Música: Modulos/Elicitacao/Plano-de-Elicitação-de-Requisitos-Música.md
        - Elicitação de Integração: Modulos/Elicitacao/Elicitação-Módulo-Integração-do-uso-do-Spotify-em-diferentes-Hardwares.md
        - Elicitação de Usuário: Modulos/Elicitacao/Plano-de-elicitação-de-requisitos-de-usuário.md
        - Elicitação de Marketing: Modulos/Elicitacao/Plano-de-Elicitação-de-Requisitos-de-Marketing.md
        - Elicitação de Monetização: Modulos/Elicitacao/Elicitação-de-requisitos-de-monetização.md
        - Elicitação de Design: Modulos/Elicitacao/Elicitação-de-requisitos-de-design.md
    - Modelagem:
        - Especificação Suplementar: Modulos/Modelagem/especificacao-suplementar.md
        - Caso de Uso Biblioteca: Modulos/Modelagem/especificacao-caso-biblioteca.md
        - Caso de Uso Gerenciar Playlists:  Modulos/Modelagem/gerenciarPlaylists.md
        - Caso de Uso Gerenciar Artistas:  Modulos/Modelagem/gerenciarArtistas.md
        - Caso de Uso Usuário: Modulos/Modelagem/caso-usuario.md
        - Caso de Uso Editar Dados: Modulos/Modelagem/especificacao-caso-editar_dados_de_conta.md
        - Caso de Uso Redes Sociais:  Modulos/Modelagem/IntegracaoRedesSociais.md
        - Caso de Uso Planos:  Modulos/Modelagem/especificacao-caso-planos.md
