site_name: Spotify

theme:
  name: 'rtd-dropdown'

pages:
    - Home: index.md
    - Pré-Rastreabilidade:
        - Rich Picture Spotify: Modulos/Pre_rastreabilidade/Rich picture/Rich-picture-spotify.md
        - Rich Picture Usuário: Modulos/Pre_rastreabilidade/Rich picture/Rich-picture-usuário.md
    - Argumentação Artista: Modulos/Pre_rastreabilidade/Argumentacao/Argumentação-artistas.md
    - Argumentação Pagamento: Modulos/Pre_rastreabilidade/Argumentacao/Argumentação-pagamento.md
    - Elicitação:
        - Elicitação de Música: Modulos/Elicitacao/Plano-de-Elicitação-de-Requisitos-Música.md
        - Elicitação de Integração: Modulos/Elicitacao/Elicitação-Módulo-Integração-do-uso-do-Spotify-em-diferentes-Hardwares.md
        - Elicitação de Usuário: Modulos/Elicitacao/Plano-de-elicitação-de-requisitos.md
        - Elicitação de Marketing: Modulos/Elicitacao/Plano-de-Elicitação-de-Requisitos-de-Marketing.md
        - Elicitação de Monetização: Modulos/Elicitacao/Elicitação-de-requisitos-de-monetização.md
        - Elicitação de Design: Modulos/Elicitacao/Elicitação-de-requisitos-de-design.md
